apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 10m
  chart:
    spec:
      chart: ./clusters/my-cluster/k10
      sourceRef:
        kind: GitRepository
        name: lux-system
        namespace: flux-system
      interval: 10m